---
title: "Eli's Data Science Portfolio"
author: "Eli Kliejunas"
date: "03/02/2022"
output: 
  html_document
---

<style type="text/css">
  body{
  font-size: 16pt;
  color: black; 
}
</style>


**Welcome to my portfolio website!** <br><br>


# **Introducing Myself**

My overarching interest as a data scientist is in deriving and communicating insights from data, both quantitative and qualitative, that advance population-wide health and overall well-being. Thus far I have focused primarily on quantitative data analysis in the field of population health as a postgraduate student at the University of Auckland. The culmination of my work there — a dissertation examining the association between socio-demographic variables and households' per capita emissions stemming from food consumption — is detailed and attached below. <br><br>

Looking ahead, I want to apply my data analysis skills in the health and social sectors to support organisations in achieving their goals. I firmly believe that in addition to intelligent data collection, management, and analysis, the thoughtful articulation and presentation of data-driven findings is absolutely essential. No matter how astute data analyses are, their insights will only support organisations' and societies' growth insofar as findings are presented intuitively to decision makers from diverse backgrounds. Therefore, I intend to work as a Data Analyst for the next several years so that I may continue developing my quantitative analysis and presentation skills while also gaining valuable experience collaborating directly with stakeholders in the health and social sectors.<br><br>

## *Programming Skills*
I am proficient in data cleaning, transforming, exploration, visualisation, and statistical analysis using R. My skills with this language were developed primarily over the course of postgraduate dissertation, then further expanded in the completion of the independent project titled "Do COVID-19 testing rates predict nationwide health outcomes." Both projects are described below.

Thus far I have worked exclusively with R, though I plan to begin learning Python in the coming months because of its enhanced machine learning and webscraping capabilities. In the meantime, I am currently completing the "SQL Fundamentals" course in the "Data Analyst in R" path on <https://www.dataquest.io/> and will move on shortly to the "Intermediate SQL in R" course. In general, I am a keen, self-directed learner, and I am constantly working to upskill my abilities in data science. <br><br>  

# **Portfolio Projects**

## *Quantifying the greenhouse gas emissions of New Zealand households’ food purchases: An analysis by socio-demographics*

For my Bachelor of Health Sciences (Honours) dissertation, I examined the  possible associations between various socio-demographic variables and dietary emissions — i.e., emissions stemming from foods' farming and processing, transit packaging, transportation, consumer packaging, warehouse and distribution, refrigeration, and retail overheads —  utilizing a large dataset of New Zealand household food purchases (n=1,998,499) recorded over the course of a year. Data cleaning, transformation, and visualization as well as statistical analyses were performed using R. For details on the entire data analysis cycle undertaken for this project, refer to the methods section (section 3) on page 27 in the accompanying <a href="https://elidjunas.github.io/portfolio/Dissertation.pdf" target="_blank">PDF</a>. The results section starting on page 38 provides examples of data presentation and visualisation. In my current position as a Research Assistant at the University of Auckland, I am preparing to submit the research for publication in an academic journal. R scripts used for this project are available upon request, however large portions of them must be redacted due to proprietary restrictions on the 2019 Nielsen Homescan® panel dataset. <br><br>

## *Do COVID-19 testing rates predict nationwide health outcomes?*

In this project I examined a large dataset on various countries' responses to the COVID-19 outbreak from the "Our World in Data" website: <https://ourworldindata.org/>. Specifically, I examined whether higher testing rates (adjusted per 100,000 people) predicted better health outcomes in terms of hospitalisations and deaths. The project can be found here: <a href="https://elidjunas.github.io/portfolio/covid_testing.html">"Do COVID-19 testing rates predict nationwide health outcomes."</a> It provides a detailed overview of my entire data analysis process from conceptualisation to data cleaning, transforming, visualising, and statistical analyses. The document provides more detail than would normally be provided outside of academia. However, I included this level of detail to fully articulate my workflow within R. <br><br>


## *Projects in Progress*
I am currently working on a project using SQL in Jupyter Notebook to query data from the CIA World Factbook, a large dataset that provides a wide range of statistics about all of the countries in the world. More on that to come soon!


